
from typing import List
from fastapi import APIRouter

from app.api.accounts.models.pydantic import AccountData


accounts = APIRouter()


@accounts.get(
    "/assignments",
    response_model=List[AccountData],
    status_code=200,
)
async def account_data():
    return [
        {
            "account":"1029328",
            "account_type":"Entertainment",
            "account_rep":"Thurston,Horace",
            "account_rep_email":"hthurston@email.com",
            "account_rep_id":"2032000112",
            "accountant1":"Furnace,Thomas",
            "accountant1_email":"tfurnace@email.com",
            "accountant2":"Brook,Patricia",
            "accountant2_email":"bpatricia@email.com",
            "accountant3":None,
            "accountant3_email":None,
            "account_updated_on":"2023-09-26 11:34:18",
            "account_updated_by":"Brook,Patricia",
            "account_added_on":"2023-01-22 10:31:28",
        },
        {
            "account":"2059520",
            "account_type":"Manufacturing",
            "account_rep":"Thurston,Horace",
            "account_rep_email":"hthurston@email.com",
            "account_rep_id":"2032000112",
            "accountant1":"Furnace,Thomas",
            "accountant1_email":"tfurnace@email.com",
            "accountant2":"Brook,Patricia",
            "accountant2_email":"bpatricia@email.com",
            "accountant3":None,
            "accountant3_email":None,
            "account_updated_on":"2023-09-26 11:34:18",
            "account_updated_by":"Brook,Patricia",
            "account_added_on":"2023-01-22 10:31:28",
        },
        {
            "account":"4039328",
            "account_type":"IT",
            "account_rep":"Douglas,Michael",
            "account_rep_email":"mdouglas@email.com",
            "account_rep_id":"3203000011",
            "accountant1":"Summer,Sam",
            "accountant1_email":"ssummer@email.com",
            "accountant2":"Fried,Bruce",
            "accountant2_email":"bfried@email.com",
            "accountant3":None,
            "accountant3_email":None,
            "account_updated_on":"2023-09-26 11:34:18",
            "account_updated_by":"Tiegan,Craig",
            "account_added_on":"2023-01-22 10:31:28",
        },
        {
            "account":"8029328",
            "account_type":"Entertainment",
            "account_rep":"Stanton,Viktor",
            "account_rep_email":"vstanton@email.com",
            "account_rep_id":"0300700218",
            "accountant1":"Love,Gina",
            "accountant1_email":"glove@email.com",
            "accountant2":"Farmer,Hank",
            "accountant2_email":"hfarmer@email.com",
            "accountant3":"Lexton,Max",
            "accountant3_email":"mlexton@email.com",
            "account_updated_on":"2023-09-26 11:34:18",
            "account_updated_by":"Brook,Patricia",
            "account_added_on":"2023-01-22 10:31:28",
        },
        {
            "account":"3149319",
            "account_type":"Advertising",
            "account_rep":"Moya,Carlos",
            "account_rep_email":"cmoya@email.com",
            "account_rep_id":"7070802318",
            "accountant1":"Siobhan,Michael",
            "accountant1_email":"msiobhan@email.com",
            "accountant2":"Stockton,Karl",
            "accountant2_email":"kstockton@email.com",
            "accountant3":None,
            "accountant3_email":None,
            "account_updated_on":"2023-09-26 11:34:18",
            "account_updated_by":"Brook,Patricia",
            "account_added_on":"2023-01-22 10:31:28",
        },
        {
            "account":"2829825",
            "account_type":"Public Affairs",
            "account_rep":"Thurston,Horace",
            "account_rep_email":"hthurston@email.com",
            "account_rep_id":"2032000112",
            "accountant1":"Stove,Gillian",
            "accountant1_email":"gstove@email.com",
            "accountant2":"Brook,Patricia",
            "accountant2_email":"bpatricia@email.com",
            "accountant3":None,
            "accountant3_email":None,
            "account_updated_on":"2023-09-26 11:34:18",
            "account_updated_by":"Brook,Patricia",
            "account_added_on":"2023-01-22 10:31:28",
        },
    ] 
